version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  # The S3 orb will setup the aws-cli and quickly copy or sync anything to s3.
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/aws-s3
  # NOTE: Environment variables containing the necessary secrets can be setup in the CircleCI UI
  # See here https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0.0


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-project:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/node:22.8.0
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - restore_cache:
          name: Restore npm Package Cache
          keys:
            - npm-checksum-{{ checksum "package-lock.json" }}
      - run:
          name: "Install Dependencies"
          command: "npm install"
      - save_cache:
          name: Save npm Package Cache
          key: npm-checksum-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: "Lint Project"
          command: "npm run lint"
      - run:
          name: "Build with Rollup"
          command: "npm run rollup"
      - run:
          name: "Build Storybook"
          command: "npm run build-storybook"
      - run:
          name: Authenticate with NPM Registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Semantic release 🚀
          command: npx semantic-release
      - aws-s3/sync:
          arguments: |
            --delete
          from: storybook-static
          to: 's3://design.pup.codes/'


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-deploy:
    jobs:
      - build-project
