version: 2.1


# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/aws-s3
  # NOTE: Environment variables containing the necessary secrets can be setup in the CircleCI UI
  # See here https://circleci.com/docs/2.0/env-vars/#setting-an-environment-variable-in-a-project
  aws-cli: circleci/aws-cli@4.0
  aws-s3: circleci/aws-s3@4.0.0

# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-project:
    docker:
      - image: cimg/node:22.8.0
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - restore_cache:
          name: Restore npm Package Cache
          keys:
            - npm-checksum-{{ checksum "package-lock.json" }}
      - run:
          name: "Install Dependencies"
          command: "npm install"
      - save_cache:
          name: Save npm Package Cache
          key: npm-checksum-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: "Lint Project"
          command: "npm run lint"
      - run:
          name: "Build with Rollup"
          command: "npm run rollup"
      - run:
          name: "Build Storybook"
          command: "npm run build-storybook"
      - aws-cli/setup
      - aws-s3/sync:
          arguments: |
            --delete
          from: storybook-static
          to: 's3://design.pup.codes/'
      - run:
          name: Authenticate with NPM Registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Semantic release 🚀
          command: npx semantic-release



# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-and-deploy:
    jobs:
      - build-project
      - s3-sync:
          requires:
            - build-project
